CREATE DATABASE TEXTGAMEJS;
USE TEXTGAMEJS;



--LOGINS

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
    USERNAME NVARCHAR(100) NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
);


-- INVENTORY/STATISTICS

DROP TABLE IF EXISTS CHARACTERDATA;
CREATE TABLE CHARACTERDATA(
    MAX_HEALTH INT NOT NULL,
    HEALTH INT NOT NULL,
    ATTACK INT NOT NULL,
    SPEED INT NOT NULL
);

DROP TABLE IF EXISTS INVENTORY;
CREATE TABLE INVENTORY (
    GOLD_PIECES INT NOT NULL,
    WEAPONS NVARCHAR(100) NOT NULL,
    ARMOUR NVARCHAR(100) NOT NULL,
    POTIONS NVARCHAR(100) NOT NULL,
    TRINKETS NVARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS STATS;
CREATE TABLE STATS(
    RATS_KILLED INT NOT NULL,
    ROOMS_EXPLORED INT NOT NULL,
    POTIONS_USED INT NOT NULL,
    HEALTH_HEALED INT NOT NULL,
    GOLD_EARNED INT NOT NULL,

);


--WEAPONS

DROP TABLE IF EXISTS WEAPON;
CREATE TABLE WEAPON(
    NAME NVARCHAR(100) NOT NULL,
    ATTACK INT NOT NULL,
    SPEED INT NOT NULL,
    RARITY INT NOT NULL
);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Wooden Sword', 10, 5, 1);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Poison Dagger', 12, 7, 2);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Guts GreatSword', 65, 1, 2);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Blood Katana', 20, 6, 3);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Frost Thrownaxe', 28, 4, 3);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Fire Staff', 25, 5, 2);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Bow of Seeking', 30, 7, 4);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Twinblade of Twigod', 45, 4, 3);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Lance of the Lance', 55, 3, 4);
INSERT INTO WEAPON (NAME,ATTACK,SPEED,RARITY) VALUES('Sword of the Baird', 60, 5, 5);
--ARMOUR
DROP TABLE IF EXISTS ARMOUR;
CREATE TABLE ARMOUR(
    NAME NVARCHAR(100) NOT NULL,
    HEALTH INT NOT NULL,
    RARITY INT NOT NULL
);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Ragged Robes', 110, 1);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Leather Armour', 150, 1);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Iron Armour', 180, 2);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Vetements of the Arachnid', 225, 2);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Cloak of the Night', 260, 3);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Stone Visage', 300, 3);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Bulwark of Hades', 350, 3);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Runite Great Armour', 450, 4);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Dragonscale Platemail', 600, 4);
INSERT INTO ARMOUR (NAME,HEALTH,RARITY) VALUES('Everprotection', 1000, 5);

--MONSTERS
DROP TABLE IF EXISTS MONSTER;
CREATE TABLE MONSTER(
    NAME NVARCHAR(100) NOT NULL,
    HEALTH INT NOT NULL,
    ATTACK INT NOT NULL,
    SPEED INT NOT NULL,
    GOLD INT NOT NULL,
    WEIGHT INT NOT NULL,
);

INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Rat', 10, 8, 5, 10, 1);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Spider', 25, 15, 4, 15, 0.9);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Crocodile', 40, 25, 3, 25, 0.8);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Skeleton', 35, 18, 4, 20, 0.7);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Hog', 20, 10, 5, 16, 0.8);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Gorilla', 50, 35, 2, 40, 0.6);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Wolf', 30, 25, 4, 45, 0.7);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Valkyrie', 70, 35, 5, 75,0.4);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Fire Elemental', 100, 20, 6, 80, 0.5);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Dwarf', 75, 40, 5, 100, 0.4);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Orc', 120, 60, 2, 110, 0.3);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Dragon',150, 75, 1, 250, 0.1);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Knight', 110, 50, 5, 125, 0.4);
INSERT INTO MONSTER (NAME,HEALTH,ATTACK,SPEED,GOLD,WEIGHT) VALUES('Wizard', 100, 40, 7, 200, 0.2);


--MULTIPLIER/BOSS

DROP TABLE IF EXISTS ENEMIES;
CREATE TABLE ENEMIES(
    LEVEL1 INT NOT NULL,
    LEVEL2 INT NOT NULL,
    LEVEL3 INT NOT NULL,
    LEVEL4 INT NOT NULL,
    LEVEL5 INT NOT NULL,
    LEVEL6 INT NOT NULL,
    LEVEL7 INT NOT NULL,
    LEVEL8 INT NOT NULL,
    LEVEL9 INT NOT NULL,
    LEVEL10 INT NOT NULL,

);

DROP TABLE IF EXISTS BOSS_NAME;
CREATE TABLE BOSS_NAME(
NAME NVARCHAR(100)
);

DROP TABLE IF EXISTS BOSS_TITLE;
CREATE TABLE BOSS_TITLE(
TITLE NVARCHAR(100)
);

-- INSERT INTO BOSS_NAME(NAME) 
-- VALUES ('Scourge','Ricord','Tim','Misra','Ranis','Idkul','Dosun','Lynurna','Eydull','Runru','Ortetta');

-- INSERT INTO BOSS_TITLE(TITLE)
-- VALUES ('the Conqueror', 'the Ascended', 'the Determined','the Lord', 'the Vigilant', 'the Keeper', 'the Champion', 'the Protector', 'the Nepotist', 'the Tyrant', 'the Wolf', 'the Emporer', 'the Former', 'the Decrepit');

